// Auto-generated by scripts/sync-coupons-from-sheet.mjs — do not edit by hand.
// Source: https://docs.google.com/spreadsheets/d/1v7QJIHRRaHiAela9PmC_e4igmUiQT6mJFn8zNOdJ-ho/edit#gid=0
const ATMAD_COUNTRY_SHEET_ROWS = [["Splash","DD14","United Arab Emirates"],["Sporter","SP61","MENA"],["Sun & Sand Sports","UKJ89","UAE KSA KWT"],["The Body Shop","OM52IP","United Arab Emirates, Saudi Arabia"],["Under Armour","GT37","MENA"],["Vogacloset","OPT5","GCC"],["Waffaraha","W28","Saudi Arabia"],["Waya","WA108","KSA"],["WHEELTOP Affiliate Program","Affiliate Tracking Link","Global"]];

const COUPON_SHEETS = [
  {
    "tabEn": "ATMAD coupon list",
    "tabAr": "قائمة أكواد ATMAD",
    "items": [
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "SKYO",
        "titleAr": "SKYO",
        "descEn": "SKYO",
        "descAr": "SKYO",
        "discountEn": "CR30",
        "discountAr": "CR30",
        "metaEn": "SKYO",
        "metaAr": "SKYO",
        "code": "CR30"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Splash",
        "titleAr": "سبلاش",
        "descEn": "خصم 20% على المنتجات غير المخفضة، خصم 5% على المنتجات المخفضة",
        "descAr": "خصم 20% على المنتجات غير المخفضة، خصم 5% على المنتجات المخفضة",
        "discountEn": "خصم 20% على المنتجات غير المخفضة، خصم 5% على المنتجات المخفضة",
        "discountAr": "خصم 20% على المنتجات غير المخفضة، خصم 5% على المنتجات المخفضة",
        "metaEn": "United Arab Emirates · Splash",
        "metaAr": "United Arab Emirates · Splash",
        "code": "DD14"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Sporter",
        "titleAr": "Sporter",
        "descEn": "Sporter",
        "descAr": "Sporter",
        "discountEn": "SP61",
        "discountAr": "SP61",
        "metaEn": "MENA · Sporter",
        "metaAr": "MENA · Sporter",
        "code": "SP61"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Squatwolf",
        "titleAr": "Squatwolf",
        "descEn": "Squatwolf",
        "descAr": "Squatwolf",
        "discountEn": "RY15",
        "discountAr": "RY15",
        "metaEn": "Squatwolf",
        "metaAr": "Squatwolf",
        "code": "RY15"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Sun & Sand Sports",
        "titleAr": "Sun & Sand Sports",
        "descEn": "Sun & Sand Sports",
        "descAr": "Sun & Sand Sports",
        "discountEn": "UKJ89",
        "discountAr": "UKJ89",
        "metaEn": "UAE KSA KWT · Sun & Sand Sports",
        "metaAr": "UAE KSA KWT · Sun & Sand Sports",
        "code": "UKJ89"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Swarovski",
        "titleAr": "Swarovski",
        "descEn": "Swarovski",
        "descAr": "Swarovski",
        "discountEn": "CX139",
        "discountAr": "CX139",
        "metaEn": "Swarovski",
        "metaAr": "Swarovski",
        "code": "CX139"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "The Body Shop",
        "titleAr": "ذا بودي شوب",
        "descEn": "خصم 10% على جميع المنتجات",
        "descAr": "خصم 10% على جميع المنتجات",
        "discountEn": "خصم 10% على جميع المنتجات",
        "discountAr": "خصم 10% على جميع المنتجات",
        "metaEn": "United Arab Emirates, Saudi Arabia · The Body Shop",
        "metaAr": "United Arab Emirates, Saudi Arabia · The Body Shop",
        "code": "OM52IP"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Toyou",
        "titleAr": "تويو",
        "descEn": "Toyou",
        "descAr": "Toyou",
        "discountEn": "CR100",
        "discountAr": "CR100",
        "metaEn": "Toyou",
        "metaAr": "Toyou",
        "code": "CR100"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Ulta Beauty",
        "titleAr": "ألتا بيوتي",
        "descEn": "Ulta Beauty",
        "descAr": "Ulta Beauty",
        "discountEn": "A9BH",
        "discountAr": "A9BH",
        "metaEn": "Ulta Beauty",
        "metaAr": "Ulta Beauty",
        "code": "A9BH"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Under Armour",
        "titleAr": "Under Armour",
        "descEn": "Under Armour",
        "descAr": "Under Armour",
        "discountEn": "GT37",
        "discountAr": "GT37",
        "metaEn": "MENA · Under Armour",
        "metaAr": "MENA · Under Armour",
        "code": "GT37"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Underhance",
        "titleAr": "Underhance",
        "descEn": "Underhance",
        "descAr": "Underhance",
        "discountEn": "UH1",
        "discountAr": "UH1",
        "metaEn": "Underhance",
        "metaAr": "Underhance",
        "code": "UH1"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Vogacloset",
        "titleAr": "Vogacloset",
        "descEn": "Vogacloset",
        "descAr": "Vogacloset",
        "discountEn": "OPT5",
        "discountAr": "OPT5",
        "metaEn": "GCC · Vogacloset",
        "metaAr": "GCC · Vogacloset",
        "code": "OPT5"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Waffaraha",
        "titleAr": "وفرها",
        "descEn": "استرداد 25 ريال",
        "descAr": "استرداد 25 ريال",
        "discountEn": "استرداد 25 ريال",
        "discountAr": "استرداد 25 ريال",
        "metaEn": "Saudi Arabia · Waffaraha",
        "metaAr": "Saudi Arabia · Waffaraha",
        "code": "W28"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "Waya",
        "titleAr": "Waya",
        "descEn": "Waya",
        "descAr": "Waya",
        "discountEn": "WA108",
        "discountAr": "WA108",
        "metaEn": "KSA · Waya",
        "metaAr": "KSA · Waya",
        "code": "WA108"
      },
      {
        "badgeEn": "Offer",
        "badgeAr": "عرض",
        "titleEn": "WHEELTOP Affiliate Program",
        "titleAr": "ويلتوب",
        "descEn": "WHEELTOP Affiliate Program",
        "descAr": "WHEELTOP Affiliate Program",
        "discountEn": "Affiliate Tracking Link",
        "discountAr": "Affiliate Tracking Link",
        "metaEn": "Global · WHEELTOP Affiliate Program",
        "metaAr": "Global · WHEELTOP Affiliate Program",
        "code": "Affiliate Tracking Link"
      }
    ]
  }
];

if (typeof window !== "undefined") {
  if (typeof COUPON_SHEETS !== "undefined") window.COUPON_SHEETS = COUPON_SHEETS;
  if (typeof ATMAD_COUNTRY_SHEET_ROWS !== "undefined") {
    window.ATMAD_COUNTRY_SHEET_ROWS = ATMAD_COUNTRY_SHEET_ROWS;
  }
}
